apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "catalog-service.fullname" . }}-config
  labels:
    {{- include "catalog-service.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.config.NODE_ENV | quote }}
  API_PREFIX: {{ .Values.config.API_PREFIX | quote }}
  APP_VERSION: {{ .Values.config.APP_VERSION | quote }}
