replicaCount: 2

image:
  repository: ghcr.io/94manuel/catalog-service-k8s
  tag: "dc9f70489689b07d7efc632d22a2129b185d25a9"
  pullPolicy: IfNotPresent

config:
  NODE_ENV: production
  API_PREFIX: api
  APP_VERSION: "1.0.0"

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: catalog.local
      paths:
        - path: /
          pathType: Prefix

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
